/* soapExternalAccessSoapProxy.cpp
   Generated by gSOAP 2.8.21 from ExternalAccess.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapExternalAccessSoapProxy.h"

ExternalAccessSoapProxy::ExternalAccessSoapProxy()
{	ExternalAccessSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ExternalAccessSoapProxy::ExternalAccessSoapProxy(const struct soap &_soap) : soap(_soap)
{ }

ExternalAccessSoapProxy::ExternalAccessSoapProxy(const char *url)
{	ExternalAccessSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

ExternalAccessSoapProxy::ExternalAccessSoapProxy(soap_mode iomode)
{	ExternalAccessSoapProxy_init(iomode, iomode);
}

ExternalAccessSoapProxy::ExternalAccessSoapProxy(const char *url, soap_mode iomode)
{	ExternalAccessSoapProxy_init(iomode, iomode);
	soap_endpoint = url;
}

ExternalAccessSoapProxy::ExternalAccessSoapProxy(soap_mode imode, soap_mode omode)
{	ExternalAccessSoapProxy_init(imode, omode);
}

ExternalAccessSoapProxy::~ExternalAccessSoapProxy()
{ }

void ExternalAccessSoapProxy::ExternalAccessSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void ExternalAccessSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void ExternalAccessSoapProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	ExternalAccessSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ExternalAccessSoapProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *ExternalAccessSoapProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *ExternalAccessSoapProxy::soap_fault()
{	return this->fault;
}

const char *ExternalAccessSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *ExternalAccessSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int ExternalAccessSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

int ExternalAccessSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void ExternalAccessSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ExternalAccessSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *ExternalAccessSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int ExternalAccessSoapProxy::wsInvokeInterface(const char *endpoint, const char *soap_action, _ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse)
{	struct soap *soap = this;
	struct __ns1__wsInvokeInterface soap_tmp___ns1__wsInvokeInterface;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.10.150/jcz_jk/ExternalAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/wsInvokeInterface";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__wsInvokeInterface.ns1__wsInvokeInterface = ns1__wsInvokeInterface;
	soap_serializeheader(soap);
	soap_serialize___ns1__wsInvokeInterface(soap, &soap_tmp___ns1__wsInvokeInterface);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__wsInvokeInterface(soap, &soap_tmp___ns1__wsInvokeInterface, "-ns1:wsInvokeInterface", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__wsInvokeInterface(soap, &soap_tmp___ns1__wsInvokeInterface, "-ns1:wsInvokeInterface", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__wsInvokeInterfaceResponse)
		return soap_closesock(soap);
	ns1__wsInvokeInterfaceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__wsInvokeInterfaceResponse.soap_get(soap, "ns1:wsInvokeInterfaceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ExternalAccessSoapProxy::GetAssemblyInfo(const char *endpoint, const char *soap_action, _ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse)
{	struct soap *soap = this;
	struct __ns1__GetAssemblyInfo soap_tmp___ns1__GetAssemblyInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.10.150/jcz_jk/ExternalAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAssemblyInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAssemblyInfo.ns1__GetAssemblyInfo = ns1__GetAssemblyInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAssemblyInfo(soap, &soap_tmp___ns1__GetAssemblyInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAssemblyInfo(soap, &soap_tmp___ns1__GetAssemblyInfo, "-ns1:GetAssemblyInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAssemblyInfo(soap, &soap_tmp___ns1__GetAssemblyInfo, "-ns1:GetAssemblyInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAssemblyInfoResponse)
		return soap_closesock(soap);
	ns1__GetAssemblyInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAssemblyInfoResponse.soap_get(soap, "ns1:GetAssemblyInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ExternalAccessSoapProxy::wsInvokeInterface_(const char *endpoint, const char *soap_action, _ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse)
{	struct soap *soap = this;
	struct __ns1__wsInvokeInterface_ soap_tmp___ns1__wsInvokeInterface_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.10.150/jcz_jk/ExternalAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/wsInvokeInterface";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__wsInvokeInterface_.ns1__wsInvokeInterface = ns1__wsInvokeInterface;
	soap_serializeheader(soap);
	soap_serialize___ns1__wsInvokeInterface_(soap, &soap_tmp___ns1__wsInvokeInterface_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__wsInvokeInterface_(soap, &soap_tmp___ns1__wsInvokeInterface_, "-ns1:wsInvokeInterface", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__wsInvokeInterface_(soap, &soap_tmp___ns1__wsInvokeInterface_, "-ns1:wsInvokeInterface", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__wsInvokeInterfaceResponse)
		return soap_closesock(soap);
	ns1__wsInvokeInterfaceResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__wsInvokeInterfaceResponse.soap_get(soap, "ns1:wsInvokeInterfaceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ExternalAccessSoapProxy::GetAssemblyInfo_(const char *endpoint, const char *soap_action, _ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse)
{	struct soap *soap = this;
	struct __ns1__GetAssemblyInfo_ soap_tmp___ns1__GetAssemblyInfo_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.10.150/jcz_jk/ExternalAccess.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAssemblyInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAssemblyInfo_.ns1__GetAssemblyInfo = ns1__GetAssemblyInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAssemblyInfo_(soap, &soap_tmp___ns1__GetAssemblyInfo_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAssemblyInfo_(soap, &soap_tmp___ns1__GetAssemblyInfo_, "-ns1:GetAssemblyInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAssemblyInfo_(soap, &soap_tmp___ns1__GetAssemblyInfo_, "-ns1:GetAssemblyInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAssemblyInfoResponse)
		return soap_closesock(soap);
	ns1__GetAssemblyInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAssemblyInfoResponse.soap_get(soap, "ns1:GetAssemblyInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
