/* soapExternalAccessSoapProxy.h
   Generated by gSOAP 2.8.21 from ExternalAccess.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapExternalAccessSoapProxy_H
#define soapExternalAccessSoapProxy_H
#include "soapH.h"

class SOAP_CMAC ExternalAccessSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'ExternalAccessSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in ExternalAccess.h (non-static)
	/// Constructor
	ExternalAccessSoapProxy();
	/// Construct from another engine state
	ExternalAccessSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	ExternalAccessSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	ExternalAccessSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ExternalAccessSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ExternalAccessSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ExternalAccessSoapProxy();
	/// Initializer used by constructors
	virtual	void ExternalAccessSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'wsInvokeInterface' (returns error code or SOAP_OK)
	virtual	int wsInvokeInterface(_ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse) { return this->wsInvokeInterface(NULL, NULL, ns1__wsInvokeInterface, ns1__wsInvokeInterfaceResponse); }
	virtual	int wsInvokeInterface(const char *endpoint, const char *soap_action, _ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse);

	/// Web service operation 'GetAssemblyInfo' (returns error code or SOAP_OK)
	virtual	int GetAssemblyInfo(_ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse) { return this->GetAssemblyInfo(NULL, NULL, ns1__GetAssemblyInfo, ns1__GetAssemblyInfoResponse); }
	virtual	int GetAssemblyInfo(const char *endpoint, const char *soap_action, _ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse);

	/// Web service operation 'wsInvokeInterface' (returns error code or SOAP_OK)
	virtual	int wsInvokeInterface_(_ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse) { return this->wsInvokeInterface_(NULL, NULL, ns1__wsInvokeInterface, ns1__wsInvokeInterfaceResponse); }
	virtual	int wsInvokeInterface_(const char *endpoint, const char *soap_action, _ns1__wsInvokeInterface *ns1__wsInvokeInterface, _ns1__wsInvokeInterfaceResponse &ns1__wsInvokeInterfaceResponse);

	/// Web service operation 'GetAssemblyInfo' (returns error code or SOAP_OK)
	virtual	int GetAssemblyInfo_(_ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse) { return this->GetAssemblyInfo_(NULL, NULL, ns1__GetAssemblyInfo, ns1__GetAssemblyInfoResponse); }
	virtual	int GetAssemblyInfo_(const char *endpoint, const char *soap_action, _ns1__GetAssemblyInfo *ns1__GetAssemblyInfo, _ns1__GetAssemblyInfoResponse &ns1__GetAssemblyInfoResponse);
};
#endif
