/* soapIBdServiceServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.21 from bd.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapIBdServiceServiceSoapBindingProxy.h"

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy()
{	IBdServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy(const char *url)
{	IBdServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy(soap_mode iomode)
{	IBdServiceServiceSoapBindingProxy_init(iomode, iomode);
}

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy(const char *url, soap_mode iomode)
{	IBdServiceServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy(soap_mode imode, soap_mode omode)
{	IBdServiceServiceSoapBindingProxy_init(imode, omode);
}

IBdServiceServiceSoapBindingProxy::~IBdServiceServiceSoapBindingProxy()
{ }

void IBdServiceServiceSoapBindingProxy::IBdServiceServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://synToCity.synchrodata.daniu.com/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void IBdServiceServiceSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void IBdServiceServiceSoapBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	IBdServiceServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void IBdServiceServiceSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *IBdServiceServiceSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *IBdServiceServiceSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *IBdServiceServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *IBdServiceServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int IBdServiceServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int IBdServiceServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void IBdServiceServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void IBdServiceServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *IBdServiceServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int IBdServiceServiceSoapBindingProxy::UploadBDResult(const char *endpoint, const char *soap_action, ns1__UploadBDResult *ns1__UploadBDResult_, ns1__UploadBDResultResponse &ns1__UploadBDResultResponse_)
{	struct soap *soap = this;
	struct __ns1__UploadBDResult soap_tmp___ns1__UploadBDResult;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.141.32.1:9999/synchrodata/webservice/bd";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadBDResult.ns1__UploadBDResult_ = ns1__UploadBDResult_;
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadBDResult(soap, &soap_tmp___ns1__UploadBDResult);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadBDResult(soap, &soap_tmp___ns1__UploadBDResult, "-ns1:UploadBDResult", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadBDResult(soap, &soap_tmp___ns1__UploadBDResult, "-ns1:UploadBDResult", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__UploadBDResultResponse_)
		return soap_closesock(soap);
	ns1__UploadBDResultResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__UploadBDResultResponse_.soap_get(soap, "ns1:UploadBDResultResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
