/* soapServiceSoapProxy.h
   Generated by gSOAP 2.8.21 from service[1].h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapServiceSoapProxy_H
#define soapServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC ServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'ServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in service[1].h (non-static)
	/// Constructor
	ServiceSoapProxy();
	/// Construct from another engine state
	ServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	ServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	ServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void ServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Sync' (returns error code or SOAP_OK)
	virtual	int Sync(_ns1__Sync *ns1__Sync, _ns1__SyncResponse &ns1__SyncResponse) { return this->Sync(NULL, NULL, ns1__Sync, ns1__SyncResponse); }
	virtual	int Sync(const char *endpoint, const char *soap_action, _ns1__Sync *ns1__Sync, _ns1__SyncResponse &ns1__SyncResponse);

	/// Web service operation 'GetInspectQueueByDate' (returns error code or SOAP_OK)
	virtual	int GetInspectQueueByDate(_ns1__GetInspectQueueByDate *ns1__GetInspectQueueByDate, _ns1__GetInspectQueueByDateResponse &ns1__GetInspectQueueByDateResponse) { return this->GetInspectQueueByDate(NULL, NULL, ns1__GetInspectQueueByDate, ns1__GetInspectQueueByDateResponse); }
	virtual	int GetInspectQueueByDate(const char *endpoint, const char *soap_action, _ns1__GetInspectQueueByDate *ns1__GetInspectQueueByDate, _ns1__GetInspectQueueByDateResponse &ns1__GetInspectQueueByDateResponse);

	/// Web service operation 'GetInspectQueueByPlateID' (returns error code or SOAP_OK)
	virtual	int GetInspectQueueByPlateID(_ns1__GetInspectQueueByPlateID *ns1__GetInspectQueueByPlateID, _ns1__GetInspectQueueByPlateIDResponse &ns1__GetInspectQueueByPlateIDResponse) { return this->GetInspectQueueByPlateID(NULL, NULL, ns1__GetInspectQueueByPlateID, ns1__GetInspectQueueByPlateIDResponse); }
	virtual	int GetInspectQueueByPlateID(const char *endpoint, const char *soap_action, _ns1__GetInspectQueueByPlateID *ns1__GetInspectQueueByPlateID, _ns1__GetInspectQueueByPlateIDResponse &ns1__GetInspectQueueByPlateIDResponse);

	/// Web service operation 'AbortInspect' (returns error code or SOAP_OK)
	virtual	int AbortInspect(_ns1__AbortInspect *ns1__AbortInspect, _ns1__AbortInspectResponse &ns1__AbortInspectResponse) { return this->AbortInspect(NULL, NULL, ns1__AbortInspect, ns1__AbortInspectResponse); }
	virtual	int AbortInspect(const char *endpoint, const char *soap_action, _ns1__AbortInspect *ns1__AbortInspect, _ns1__AbortInspectResponse &ns1__AbortInspectResponse);

	/// Web service operation 'BeginRecord' (returns error code or SOAP_OK)
	virtual	int BeginRecord(_ns1__BeginRecord *ns1__BeginRecord, _ns1__BeginRecordResponse &ns1__BeginRecordResponse) { return this->BeginRecord(NULL, NULL, ns1__BeginRecord, ns1__BeginRecordResponse); }
	virtual	int BeginRecord(const char *endpoint, const char *soap_action, _ns1__BeginRecord *ns1__BeginRecord, _ns1__BeginRecordResponse &ns1__BeginRecordResponse);

	/// Web service operation 'EndRecord' (returns error code or SOAP_OK)
	virtual	int EndRecord(_ns1__EndRecord *ns1__EndRecord, _ns1__EndRecordResponse &ns1__EndRecordResponse) { return this->EndRecord(NULL, NULL, ns1__EndRecord, ns1__EndRecordResponse); }
	virtual	int EndRecord(const char *endpoint, const char *soap_action, _ns1__EndRecord *ns1__EndRecord, _ns1__EndRecordResponse &ns1__EndRecordResponse);

	/// Web service operation 'BeginInspect' (returns error code or SOAP_OK)
	virtual	int BeginInspect(_ns1__BeginInspect *ns1__BeginInspect, _ns1__BeginInspectResponse &ns1__BeginInspectResponse) { return this->BeginInspect(NULL, NULL, ns1__BeginInspect, ns1__BeginInspectResponse); }
	virtual	int BeginInspect(const char *endpoint, const char *soap_action, _ns1__BeginInspect *ns1__BeginInspect, _ns1__BeginInspectResponse &ns1__BeginInspectResponse);

	/// Web service operation 'GetLimit' (returns error code or SOAP_OK)
	virtual	int GetLimit(_ns1__GetLimit *ns1__GetLimit, _ns1__GetLimitResponse &ns1__GetLimitResponse) { return this->GetLimit(NULL, NULL, ns1__GetLimit, ns1__GetLimitResponse); }
	virtual	int GetLimit(const char *endpoint, const char *soap_action, _ns1__GetLimit *ns1__GetLimit, _ns1__GetLimitResponse &ns1__GetLimitResponse);

	/// Web service operation 'TakePhoto' (returns error code or SOAP_OK)
	virtual	int TakePhoto(_ns1__TakePhoto *ns1__TakePhoto, _ns1__TakePhotoResponse &ns1__TakePhotoResponse) { return this->TakePhoto(NULL, NULL, ns1__TakePhoto, ns1__TakePhotoResponse); }
	virtual	int TakePhoto(const char *endpoint, const char *soap_action, _ns1__TakePhoto *ns1__TakePhoto, _ns1__TakePhotoResponse &ns1__TakePhotoResponse);

	/// Web service operation 'WJTakePhoto' (returns error code or SOAP_OK)
	virtual	int WJTakePhoto(_ns1__WJTakePhoto *ns1__WJTakePhoto, _ns1__WJTakePhotoResponse &ns1__WJTakePhotoResponse) { return this->WJTakePhoto(NULL, NULL, ns1__WJTakePhoto, ns1__WJTakePhotoResponse); }
	virtual	int WJTakePhoto(const char *endpoint, const char *soap_action, _ns1__WJTakePhoto *ns1__WJTakePhoto, _ns1__WJTakePhotoResponse &ns1__WJTakePhotoResponse);

	/// Web service operation 'StopInspect' (returns error code or SOAP_OK)
	virtual	int StopInspect(_ns1__StopInspect *ns1__StopInspect, _ns1__StopInspectResponse &ns1__StopInspectResponse) { return this->StopInspect(NULL, NULL, ns1__StopInspect, ns1__StopInspectResponse); }
	virtual	int StopInspect(const char *endpoint, const char *soap_action, _ns1__StopInspect *ns1__StopInspect, _ns1__StopInspectResponse &ns1__StopInspectResponse);

	/// Web service operation 'EndInspect' (returns error code or SOAP_OK)
	virtual	int EndInspect(_ns1__EndInspect *ns1__EndInspect, _ns1__EndInspectResponse &ns1__EndInspectResponse) { return this->EndInspect(NULL, NULL, ns1__EndInspect, ns1__EndInspectResponse); }
	virtual	int EndInspect(const char *endpoint, const char *soap_action, _ns1__EndInspect *ns1__EndInspect, _ns1__EndInspectResponse &ns1__EndInspectResponse);

	/// Web service operation 'UploadSelfTestData' (returns error code or SOAP_OK)
	virtual	int UploadSelfTestData(_ns1__UploadSelfTestData *ns1__UploadSelfTestData, _ns1__UploadSelfTestDataResponse &ns1__UploadSelfTestDataResponse) { return this->UploadSelfTestData(NULL, NULL, ns1__UploadSelfTestData, ns1__UploadSelfTestDataResponse); }
	virtual	int UploadSelfTestData(const char *endpoint, const char *soap_action, _ns1__UploadSelfTestData *ns1__UploadSelfTestData, _ns1__UploadSelfTestDataResponse &ns1__UploadSelfTestDataResponse);

	/// Web service operation 'UploadRealtimeData' (returns error code or SOAP_OK)
	virtual	int UploadRealtimeData(_ns1__UploadRealtimeData *ns1__UploadRealtimeData, _ns1__UploadRealtimeDataResponse &ns1__UploadRealtimeDataResponse) { return this->UploadRealtimeData(NULL, NULL, ns1__UploadRealtimeData, ns1__UploadRealtimeDataResponse); }
	virtual	int UploadRealtimeData(const char *endpoint, const char *soap_action, _ns1__UploadRealtimeData *ns1__UploadRealtimeData, _ns1__UploadRealtimeDataResponse &ns1__UploadRealtimeDataResponse);

	/// Web service operation 'GetInspectionInfo' (returns error code or SOAP_OK)
	virtual	int GetInspectionInfo(_ns1__GetInspectionInfo *ns1__GetInspectionInfo, _ns1__GetInspectionInfoResponse &ns1__GetInspectionInfoResponse) { return this->GetInspectionInfo(NULL, NULL, ns1__GetInspectionInfo, ns1__GetInspectionInfoResponse); }
	virtual	int GetInspectionInfo(const char *endpoint, const char *soap_action, _ns1__GetInspectionInfo *ns1__GetInspectionInfo, _ns1__GetInspectionInfoResponse &ns1__GetInspectionInfoResponse);

	/// Web service operation 'BeginCalibrate' (returns error code or SOAP_OK)
	virtual	int BeginCalibrate(_ns1__BeginCalibrate *ns1__BeginCalibrate, _ns1__BeginCalibrateResponse &ns1__BeginCalibrateResponse) { return this->BeginCalibrate(NULL, NULL, ns1__BeginCalibrate, ns1__BeginCalibrateResponse); }
	virtual	int BeginCalibrate(const char *endpoint, const char *soap_action, _ns1__BeginCalibrate *ns1__BeginCalibrate, _ns1__BeginCalibrateResponse &ns1__BeginCalibrateResponse);

	/// Web service operation 'UploadCalibrateData' (returns error code or SOAP_OK)
	virtual	int UploadCalibrateData(_ns1__UploadCalibrateData *ns1__UploadCalibrateData, _ns1__UploadCalibrateDataResponse &ns1__UploadCalibrateDataResponse) { return this->UploadCalibrateData(NULL, NULL, ns1__UploadCalibrateData, ns1__UploadCalibrateDataResponse); }
	virtual	int UploadCalibrateData(const char *endpoint, const char *soap_action, _ns1__UploadCalibrateData *ns1__UploadCalibrateData, _ns1__UploadCalibrateDataResponse &ns1__UploadCalibrateDataResponse);

	/// Web service operation 'EndCalibrate' (returns error code or SOAP_OK)
	virtual	int EndCalibrate(_ns1__EndCalibrate *ns1__EndCalibrate, _ns1__EndCalibrateResponse &ns1__EndCalibrateResponse) { return this->EndCalibrate(NULL, NULL, ns1__EndCalibrate, ns1__EndCalibrateResponse); }
	virtual	int EndCalibrate(const char *endpoint, const char *soap_action, _ns1__EndCalibrate *ns1__EndCalibrate, _ns1__EndCalibrateResponse &ns1__EndCalibrateResponse);

	/// Web service operation 'TestPhoto' (returns error code or SOAP_OK)
	virtual	int TestPhoto(_ns1__TestPhoto *ns1__TestPhoto, _ns1__TestPhotoResponse &ns1__TestPhotoResponse) { return this->TestPhoto(NULL, NULL, ns1__TestPhoto, ns1__TestPhotoResponse); }
	virtual	int TestPhoto(const char *endpoint, const char *soap_action, _ns1__TestPhoto *ns1__TestPhoto, _ns1__TestPhotoResponse &ns1__TestPhotoResponse);

	/// Web service operation 'FuelEvaporationInspect' (returns error code or SOAP_OK)
	virtual	int FuelEvaporationInspect(_ns1__FuelEvaporationInspect *ns1__FuelEvaporationInspect, _ns1__FuelEvaporationInspectResponse &ns1__FuelEvaporationInspectResponse) { return this->FuelEvaporationInspect(NULL, NULL, ns1__FuelEvaporationInspect, ns1__FuelEvaporationInspectResponse); }
	virtual	int FuelEvaporationInspect(const char *endpoint, const char *soap_action, _ns1__FuelEvaporationInspect *ns1__FuelEvaporationInspect, _ns1__FuelEvaporationInspectResponse &ns1__FuelEvaporationInspectResponse);

	/// Web service operation 'GetInspectParams' (returns error code or SOAP_OK)
	virtual	int GetInspectParams(_ns1__GetInspectParams *ns1__GetInspectParams, _ns1__GetInspectParamsResponse &ns1__GetInspectParamsResponse) { return this->GetInspectParams(NULL, NULL, ns1__GetInspectParams, ns1__GetInspectParamsResponse); }
	virtual	int GetInspectParams(const char *endpoint, const char *soap_action, _ns1__GetInspectParams *ns1__GetInspectParams, _ns1__GetInspectParamsResponse &ns1__GetInspectParamsResponse);

	/// Web service operation 'GetOtherInspectQueueByPlateID' (returns error code or SOAP_OK)
	virtual	int GetOtherInspectQueueByPlateID(_ns1__GetOtherInspectQueueByPlateID *ns1__GetOtherInspectQueueByPlateID, _ns1__GetOtherInspectQueueByPlateIDResponse &ns1__GetOtherInspectQueueByPlateIDResponse) { return this->GetOtherInspectQueueByPlateID(NULL, NULL, ns1__GetOtherInspectQueueByPlateID, ns1__GetOtherInspectQueueByPlateIDResponse); }
	virtual	int GetOtherInspectQueueByPlateID(const char *endpoint, const char *soap_action, _ns1__GetOtherInspectQueueByPlateID *ns1__GetOtherInspectQueueByPlateID, _ns1__GetOtherInspectQueueByPlateIDResponse &ns1__GetOtherInspectQueueByPlateIDResponse);

	/// Web service operation 'GetOtherInspectQueueByDate' (returns error code or SOAP_OK)
	virtual	int GetOtherInspectQueueByDate(_ns1__GetOtherInspectQueueByDate *ns1__GetOtherInspectQueueByDate, _ns1__GetOtherInspectQueueByDateResponse &ns1__GetOtherInspectQueueByDateResponse) { return this->GetOtherInspectQueueByDate(NULL, NULL, ns1__GetOtherInspectQueueByDate, ns1__GetOtherInspectQueueByDateResponse); }
	virtual	int GetOtherInspectQueueByDate(const char *endpoint, const char *soap_action, _ns1__GetOtherInspectQueueByDate *ns1__GetOtherInspectQueueByDate, _ns1__GetOtherInspectQueueByDateResponse &ns1__GetOtherInspectQueueByDateResponse);

	/// Web service operation 'OBDInspect' (returns error code or SOAP_OK)
	virtual	int OBDInspect(_ns1__OBDInspect *ns1__OBDInspect, _ns1__OBDInspectResponse &ns1__OBDInspectResponse) { return this->OBDInspect(NULL, NULL, ns1__OBDInspect, ns1__OBDInspectResponse); }
	virtual	int OBDInspect(const char *endpoint, const char *soap_action, _ns1__OBDInspect *ns1__OBDInspect, _ns1__OBDInspectResponse &ns1__OBDInspectResponse);

	/// Web service operation 'OBDTXCheck' (returns error code or SOAP_OK)
	virtual	int OBDTXCheck(_ns1__OBDTXCheck *ns1__OBDTXCheck, _ns1__OBDTXCheckResponse &ns1__OBDTXCheckResponse) { return this->OBDTXCheck(NULL, NULL, ns1__OBDTXCheck, ns1__OBDTXCheckResponse); }
	virtual	int OBDTXCheck(const char *endpoint, const char *soap_action, _ns1__OBDTXCheck *ns1__OBDTXCheck, _ns1__OBDTXCheckResponse &ns1__OBDTXCheckResponse);

	/// Web service operation 'Sync' (returns error code or SOAP_OK)
	virtual	int Sync_(_ns1__Sync *ns1__Sync, _ns1__SyncResponse &ns1__SyncResponse) { return this->Sync_(NULL, NULL, ns1__Sync, ns1__SyncResponse); }
	virtual	int Sync_(const char *endpoint, const char *soap_action, _ns1__Sync *ns1__Sync, _ns1__SyncResponse &ns1__SyncResponse);

	/// Web service operation 'GetInspectQueueByDate' (returns error code or SOAP_OK)
	virtual	int GetInspectQueueByDate_(_ns1__GetInspectQueueByDate *ns1__GetInspectQueueByDate, _ns1__GetInspectQueueByDateResponse &ns1__GetInspectQueueByDateResponse) { return this->GetInspectQueueByDate_(NULL, NULL, ns1__GetInspectQueueByDate, ns1__GetInspectQueueByDateResponse); }
	virtual	int GetInspectQueueByDate_(const char *endpoint, const char *soap_action, _ns1__GetInspectQueueByDate *ns1__GetInspectQueueByDate, _ns1__GetInspectQueueByDateResponse &ns1__GetInspectQueueByDateResponse);

	/// Web service operation 'GetInspectQueueByPlateID' (returns error code or SOAP_OK)
	virtual	int GetInspectQueueByPlateID_(_ns1__GetInspectQueueByPlateID *ns1__GetInspectQueueByPlateID, _ns1__GetInspectQueueByPlateIDResponse &ns1__GetInspectQueueByPlateIDResponse) { return this->GetInspectQueueByPlateID_(NULL, NULL, ns1__GetInspectQueueByPlateID, ns1__GetInspectQueueByPlateIDResponse); }
	virtual	int GetInspectQueueByPlateID_(const char *endpoint, const char *soap_action, _ns1__GetInspectQueueByPlateID *ns1__GetInspectQueueByPlateID, _ns1__GetInspectQueueByPlateIDResponse &ns1__GetInspectQueueByPlateIDResponse);

	/// Web service operation 'AbortInspect' (returns error code or SOAP_OK)
	virtual	int AbortInspect_(_ns1__AbortInspect *ns1__AbortInspect, _ns1__AbortInspectResponse &ns1__AbortInspectResponse) { return this->AbortInspect_(NULL, NULL, ns1__AbortInspect, ns1__AbortInspectResponse); }
	virtual	int AbortInspect_(const char *endpoint, const char *soap_action, _ns1__AbortInspect *ns1__AbortInspect, _ns1__AbortInspectResponse &ns1__AbortInspectResponse);

	/// Web service operation 'BeginRecord' (returns error code or SOAP_OK)
	virtual	int BeginRecord_(_ns1__BeginRecord *ns1__BeginRecord, _ns1__BeginRecordResponse &ns1__BeginRecordResponse) { return this->BeginRecord_(NULL, NULL, ns1__BeginRecord, ns1__BeginRecordResponse); }
	virtual	int BeginRecord_(const char *endpoint, const char *soap_action, _ns1__BeginRecord *ns1__BeginRecord, _ns1__BeginRecordResponse &ns1__BeginRecordResponse);

	/// Web service operation 'EndRecord' (returns error code or SOAP_OK)
	virtual	int EndRecord_(_ns1__EndRecord *ns1__EndRecord, _ns1__EndRecordResponse &ns1__EndRecordResponse) { return this->EndRecord_(NULL, NULL, ns1__EndRecord, ns1__EndRecordResponse); }
	virtual	int EndRecord_(const char *endpoint, const char *soap_action, _ns1__EndRecord *ns1__EndRecord, _ns1__EndRecordResponse &ns1__EndRecordResponse);

	/// Web service operation 'BeginInspect' (returns error code or SOAP_OK)
	virtual	int BeginInspect_(_ns1__BeginInspect *ns1__BeginInspect, _ns1__BeginInspectResponse &ns1__BeginInspectResponse) { return this->BeginInspect_(NULL, NULL, ns1__BeginInspect, ns1__BeginInspectResponse); }
	virtual	int BeginInspect_(const char *endpoint, const char *soap_action, _ns1__BeginInspect *ns1__BeginInspect, _ns1__BeginInspectResponse &ns1__BeginInspectResponse);

	/// Web service operation 'GetLimit' (returns error code or SOAP_OK)
	virtual	int GetLimit_(_ns1__GetLimit *ns1__GetLimit, _ns1__GetLimitResponse &ns1__GetLimitResponse) { return this->GetLimit_(NULL, NULL, ns1__GetLimit, ns1__GetLimitResponse); }
	virtual	int GetLimit_(const char *endpoint, const char *soap_action, _ns1__GetLimit *ns1__GetLimit, _ns1__GetLimitResponse &ns1__GetLimitResponse);

	/// Web service operation 'TakePhoto' (returns error code or SOAP_OK)
	virtual	int TakePhoto_(_ns1__TakePhoto *ns1__TakePhoto, _ns1__TakePhotoResponse &ns1__TakePhotoResponse) { return this->TakePhoto_(NULL, NULL, ns1__TakePhoto, ns1__TakePhotoResponse); }
	virtual	int TakePhoto_(const char *endpoint, const char *soap_action, _ns1__TakePhoto *ns1__TakePhoto, _ns1__TakePhotoResponse &ns1__TakePhotoResponse);

	/// Web service operation 'WJTakePhoto' (returns error code or SOAP_OK)
	virtual	int WJTakePhoto_(_ns1__WJTakePhoto *ns1__WJTakePhoto, _ns1__WJTakePhotoResponse &ns1__WJTakePhotoResponse) { return this->WJTakePhoto_(NULL, NULL, ns1__WJTakePhoto, ns1__WJTakePhotoResponse); }
	virtual	int WJTakePhoto_(const char *endpoint, const char *soap_action, _ns1__WJTakePhoto *ns1__WJTakePhoto, _ns1__WJTakePhotoResponse &ns1__WJTakePhotoResponse);

	/// Web service operation 'StopInspect' (returns error code or SOAP_OK)
	virtual	int StopInspect_(_ns1__StopInspect *ns1__StopInspect, _ns1__StopInspectResponse &ns1__StopInspectResponse) { return this->StopInspect_(NULL, NULL, ns1__StopInspect, ns1__StopInspectResponse); }
	virtual	int StopInspect_(const char *endpoint, const char *soap_action, _ns1__StopInspect *ns1__StopInspect, _ns1__StopInspectResponse &ns1__StopInspectResponse);

	/// Web service operation 'EndInspect' (returns error code or SOAP_OK)
	virtual	int EndInspect_(_ns1__EndInspect *ns1__EndInspect, _ns1__EndInspectResponse &ns1__EndInspectResponse) { return this->EndInspect_(NULL, NULL, ns1__EndInspect, ns1__EndInspectResponse); }
	virtual	int EndInspect_(const char *endpoint, const char *soap_action, _ns1__EndInspect *ns1__EndInspect, _ns1__EndInspectResponse &ns1__EndInspectResponse);

	/// Web service operation 'UploadSelfTestData' (returns error code or SOAP_OK)
	virtual	int UploadSelfTestData_(_ns1__UploadSelfTestData *ns1__UploadSelfTestData, _ns1__UploadSelfTestDataResponse &ns1__UploadSelfTestDataResponse) { return this->UploadSelfTestData_(NULL, NULL, ns1__UploadSelfTestData, ns1__UploadSelfTestDataResponse); }
	virtual	int UploadSelfTestData_(const char *endpoint, const char *soap_action, _ns1__UploadSelfTestData *ns1__UploadSelfTestData, _ns1__UploadSelfTestDataResponse &ns1__UploadSelfTestDataResponse);

	/// Web service operation 'UploadRealtimeData' (returns error code or SOAP_OK)
	virtual	int UploadRealtimeData_(_ns1__UploadRealtimeData *ns1__UploadRealtimeData, _ns1__UploadRealtimeDataResponse &ns1__UploadRealtimeDataResponse) { return this->UploadRealtimeData_(NULL, NULL, ns1__UploadRealtimeData, ns1__UploadRealtimeDataResponse); }
	virtual	int UploadRealtimeData_(const char *endpoint, const char *soap_action, _ns1__UploadRealtimeData *ns1__UploadRealtimeData, _ns1__UploadRealtimeDataResponse &ns1__UploadRealtimeDataResponse);

	/// Web service operation 'GetInspectionInfo' (returns error code or SOAP_OK)
	virtual	int GetInspectionInfo_(_ns1__GetInspectionInfo *ns1__GetInspectionInfo, _ns1__GetInspectionInfoResponse &ns1__GetInspectionInfoResponse) { return this->GetInspectionInfo_(NULL, NULL, ns1__GetInspectionInfo, ns1__GetInspectionInfoResponse); }
	virtual	int GetInspectionInfo_(const char *endpoint, const char *soap_action, _ns1__GetInspectionInfo *ns1__GetInspectionInfo, _ns1__GetInspectionInfoResponse &ns1__GetInspectionInfoResponse);

	/// Web service operation 'BeginCalibrate' (returns error code or SOAP_OK)
	virtual	int BeginCalibrate_(_ns1__BeginCalibrate *ns1__BeginCalibrate, _ns1__BeginCalibrateResponse &ns1__BeginCalibrateResponse) { return this->BeginCalibrate_(NULL, NULL, ns1__BeginCalibrate, ns1__BeginCalibrateResponse); }
	virtual	int BeginCalibrate_(const char *endpoint, const char *soap_action, _ns1__BeginCalibrate *ns1__BeginCalibrate, _ns1__BeginCalibrateResponse &ns1__BeginCalibrateResponse);

	/// Web service operation 'UploadCalibrateData' (returns error code or SOAP_OK)
	virtual	int UploadCalibrateData_(_ns1__UploadCalibrateData *ns1__UploadCalibrateData, _ns1__UploadCalibrateDataResponse &ns1__UploadCalibrateDataResponse) { return this->UploadCalibrateData_(NULL, NULL, ns1__UploadCalibrateData, ns1__UploadCalibrateDataResponse); }
	virtual	int UploadCalibrateData_(const char *endpoint, const char *soap_action, _ns1__UploadCalibrateData *ns1__UploadCalibrateData, _ns1__UploadCalibrateDataResponse &ns1__UploadCalibrateDataResponse);

	/// Web service operation 'EndCalibrate' (returns error code or SOAP_OK)
	virtual	int EndCalibrate_(_ns1__EndCalibrate *ns1__EndCalibrate, _ns1__EndCalibrateResponse &ns1__EndCalibrateResponse) { return this->EndCalibrate_(NULL, NULL, ns1__EndCalibrate, ns1__EndCalibrateResponse); }
	virtual	int EndCalibrate_(const char *endpoint, const char *soap_action, _ns1__EndCalibrate *ns1__EndCalibrate, _ns1__EndCalibrateResponse &ns1__EndCalibrateResponse);

	/// Web service operation 'TestPhoto' (returns error code or SOAP_OK)
	virtual	int TestPhoto_(_ns1__TestPhoto *ns1__TestPhoto, _ns1__TestPhotoResponse &ns1__TestPhotoResponse) { return this->TestPhoto_(NULL, NULL, ns1__TestPhoto, ns1__TestPhotoResponse); }
	virtual	int TestPhoto_(const char *endpoint, const char *soap_action, _ns1__TestPhoto *ns1__TestPhoto, _ns1__TestPhotoResponse &ns1__TestPhotoResponse);

	/// Web service operation 'FuelEvaporationInspect' (returns error code or SOAP_OK)
	virtual	int FuelEvaporationInspect_(_ns1__FuelEvaporationInspect *ns1__FuelEvaporationInspect, _ns1__FuelEvaporationInspectResponse &ns1__FuelEvaporationInspectResponse) { return this->FuelEvaporationInspect_(NULL, NULL, ns1__FuelEvaporationInspect, ns1__FuelEvaporationInspectResponse); }
	virtual	int FuelEvaporationInspect_(const char *endpoint, const char *soap_action, _ns1__FuelEvaporationInspect *ns1__FuelEvaporationInspect, _ns1__FuelEvaporationInspectResponse &ns1__FuelEvaporationInspectResponse);

	/// Web service operation 'GetInspectParams' (returns error code or SOAP_OK)
	virtual	int GetInspectParams_(_ns1__GetInspectParams *ns1__GetInspectParams, _ns1__GetInspectParamsResponse &ns1__GetInspectParamsResponse) { return this->GetInspectParams_(NULL, NULL, ns1__GetInspectParams, ns1__GetInspectParamsResponse); }
	virtual	int GetInspectParams_(const char *endpoint, const char *soap_action, _ns1__GetInspectParams *ns1__GetInspectParams, _ns1__GetInspectParamsResponse &ns1__GetInspectParamsResponse);

	/// Web service operation 'GetOtherInspectQueueByPlateID' (returns error code or SOAP_OK)
	virtual	int GetOtherInspectQueueByPlateID_(_ns1__GetOtherInspectQueueByPlateID *ns1__GetOtherInspectQueueByPlateID, _ns1__GetOtherInspectQueueByPlateIDResponse &ns1__GetOtherInspectQueueByPlateIDResponse) { return this->GetOtherInspectQueueByPlateID_(NULL, NULL, ns1__GetOtherInspectQueueByPlateID, ns1__GetOtherInspectQueueByPlateIDResponse); }
	virtual	int GetOtherInspectQueueByPlateID_(const char *endpoint, const char *soap_action, _ns1__GetOtherInspectQueueByPlateID *ns1__GetOtherInspectQueueByPlateID, _ns1__GetOtherInspectQueueByPlateIDResponse &ns1__GetOtherInspectQueueByPlateIDResponse);

	/// Web service operation 'GetOtherInspectQueueByDate' (returns error code or SOAP_OK)
	virtual	int GetOtherInspectQueueByDate_(_ns1__GetOtherInspectQueueByDate *ns1__GetOtherInspectQueueByDate, _ns1__GetOtherInspectQueueByDateResponse &ns1__GetOtherInspectQueueByDateResponse) { return this->GetOtherInspectQueueByDate_(NULL, NULL, ns1__GetOtherInspectQueueByDate, ns1__GetOtherInspectQueueByDateResponse); }
	virtual	int GetOtherInspectQueueByDate_(const char *endpoint, const char *soap_action, _ns1__GetOtherInspectQueueByDate *ns1__GetOtherInspectQueueByDate, _ns1__GetOtherInspectQueueByDateResponse &ns1__GetOtherInspectQueueByDateResponse);

	/// Web service operation 'OBDInspect' (returns error code or SOAP_OK)
	virtual	int OBDInspect_(_ns1__OBDInspect *ns1__OBDInspect, _ns1__OBDInspectResponse &ns1__OBDInspectResponse) { return this->OBDInspect_(NULL, NULL, ns1__OBDInspect, ns1__OBDInspectResponse); }
	virtual	int OBDInspect_(const char *endpoint, const char *soap_action, _ns1__OBDInspect *ns1__OBDInspect, _ns1__OBDInspectResponse &ns1__OBDInspectResponse);

	/// Web service operation 'OBDTXCheck' (returns error code or SOAP_OK)
	virtual	int OBDTXCheck_(_ns1__OBDTXCheck *ns1__OBDTXCheck, _ns1__OBDTXCheckResponse &ns1__OBDTXCheckResponse) { return this->OBDTXCheck_(NULL, NULL, ns1__OBDTXCheck, ns1__OBDTXCheckResponse); }
	virtual	int OBDTXCheck_(const char *endpoint, const char *soap_action, _ns1__OBDTXCheck *ns1__OBDTXCheck, _ns1__OBDTXCheckResponse &ns1__OBDTXCheckResponse);
};
#endif
